services:
  database:
      build: "db"
      environment:
        - POSTGRES_DB=db
        - POSTGRES_USER=usr
        - POSTGRES_PASSWORD=pwd
      volumes:
        - db-volume:/var/lib/postgresql/data
      networks: 
        - app-network
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U usr -d db -h localhost"]
        interval: 5s
        timeout: 3s
        retries: 10

  simple-api:
      build: "simple-api"
      environment:
        - DATABASE_URL=jdbc:postgresql://database:5432/db
        - DATABASE_USERNAME=usr
        - DATABASE_PASSWORD=pwd
        - DATABASE_DB=db
      depends_on:
        - database
      networks:
        - app-network

  httpd:
      build: "http-server"
      ports:
        - "81:80"
      depends_on:
        - simple-api
      networks:
        - app-network

networks:
  app-network:

volumes:
  db-volume:
