name: CI devops 2025

on:
  push:
    branches:
      - main
      - develop
      - TP2
  pull_request:
    branches:
      - main
      - develop
      - TP2

jobs:
  test-backend:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
      
      - name: Build and test with Maven
        run: mvn clean verify
